import re

def levenshtein(a: str, b: str) -> int:
    """Compute Levenshtein distance between two strings."""
    if len(a) < len(b):
        a, b = b, a
    prev = range(len(b) + 1)
    for i, ca in enumerate(a):
        curr = [i + 1]
        for j, cb in enumerate(b):
            cost = 0 if ca == cb else 1
            curr.append(min(curr[-1] + 1, prev[j + 1] + 1, prev[j] + cost))
        prev = curr
    return prev[-1]

# Core English dictionary (academic + common words)
DICTIONARY = {
    # Common words
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "can", "shall", "must", "need", "dare",
    "i", "you", "he", "she", "it", "we", "they", "me", "him", "her",
    "us", "them", "my", "your", "his", "its", "our", "their",
    "this", "that", "these", "those", "here", "there",
    "and", "or", "but", "if", "because", "since", "while", "although",
    "so", "yet", "for", "nor", "not",
    "in", "on", "at", "by", "with", "from", "to", "of", "about",
    "into", "through", "during", "before", "after", "above", "below",
    "between", "under", "over", "out", "off", "up", "down",
    "what", "which", "who", "whom", "whose", "why", "how",
    "when", "where", "all", "each", "every", "both", "few", "many",
    "much", "some", "any", "no", "none", "one", "two", "three",
    "other", "another", "such", "own", "same", "different",
    "good", "bad", "new", "old", "big", "small", "large", "great",
    "long", "short", "high", "low", "right", "wrong", "true", "false",
    "first", "last", "next", "previous", "final", "early", "late",
    "get", "got", "make", "made", "take", "took", "give", "given",
    "find", "found", "know", "knew", "known", "think", "thought",
    "come", "came", "go", "went", "gone", "see", "saw", "seen",
    "say", "said", "tell", "told", "ask", "asked", "use", "used",
    "need", "want", "like", "work", "call", "try", "ask", "help",
    "show", "start", "end", "keep", "hold", "look", "let", "begin",
    "mean", "set", "put", "run", "move", "live", "believe", "feel",
    "seem", "bring", "leave", "happen", "turn", "bring", "change",
    "understand", "remember", "create", "cause", "allow", "expect",
    "learn", "study", "teach",
    "just", "also", "very", "well", "even", "still", "always",
    "never", "often", "usually", "sometimes", "already", "now", "then",
    "here", "there", "only", "really", "quite", "too", "much", "more",
    "most", "less", "least", "enough",
    "thing", "way", "time", "year", "day", "man", "woman", "child",
    "world", "life", "hand", "part", "place", "case", "week", "number",
    "group", "point", "state", "family", "school", "student", "teacher",
    "book", "word", "line", "kind", "form", "end", "side", "fact",
    "question", "answer", "example", "idea", "problem", "reason",
    "result", "difference", "process", "system", "information",
    "science", "history", "language", "english", "math", "art",
    "music", "sport", "game",
    "name", "type", "level", "class", "room", "home", "city", "country",
    "state", "area", "water", "food", "air", "sun", "light", "color",
    "body", "heart", "brain", "blood", "bone", "skin", "eye", "ear",
    "hand", "foot", "head", "face", "mind",
    "plant", "animal", "tree", "flower", "leaf", "root", "seed",
    "bird", "fish", "human", "cell", "gene", "dna", "protein",
    "atom", "molecule", "element", "compound", "mixture",
    "energy", "force", "motion", "speed", "mass", "weight",
    "number", "digit", "value", "equation", "graph", "formula",
    "read", "write", "draw", "count", "measure", "calculate",
    "add", "subtract", "multiply", "divide", "solve", "prove",
    "listen", "speak", "explain", "describe", "define",
    "nature", "space", "earth", "moon", "sun", "star", "planet",
    "heat", "cold", "hot", "warm", "cool", "temperature",
    "sound", "noise", "voice", "music", "note", "rhythm",
    "picture", "image", "diagram", "map", "chart", "table",
    "simple", "complex", "easy", "hard", "difficult", "possible",
    "important", "necessary", "common", "special", "specific",
    "general", "particular", "natural", "human", "social",
    "political", "economic", "cultural", "modern", "ancient",
    "main", "major", "minor", "central", "local", "global",
    "open", "close", "begin", "end", "start", "finish", "stop",
    "continue", "increase", "decrease", "grow", "develop", "improve",
    "include", "contain", "consist", "involve", "require",
    "provide", "produce", "create", "build", "form", "make",
    "break", "destroy", "damage", "fix", "repair",
    "protect", "save", "keep", "store", "preserve",
    "connect", "separate", "combine", "divide", "split",
    "collect", "gather", "spread", "distribute",
    "push", "pull", "lift", "drop", "carry", "catch", "throw",
    "enter", "exit", "arrive", "leave", "return", "travel",
    "stand", "sit", "lie", "rise", "fall", "sleep", "wake",
    "eat", "drink", "breathe",
    "think", "believe", "know", "understand", "remember",
    "forget", "consider", "decide", "choose", "select",
    "compare", "contrast", "analyze", "examine", "study",
    "observe", "notice", "watch", "look", "see",
    "listen", "hear", "feel", "touch", "smell", "taste",
    "speak", "talk", "say", "tell", "ask", "answer",
    "read", "write", "type", "print", "copy", "paste",
    "send", "receive", "share", "give", "take", "bring",
    "hello", "hi", "hey", "goodbye", "bye", "thanks", "please",
    "sorry", "yes", "no", "okay", "ok", "sure", "maybe",
    "actually", "basically", "probably", "definitely",
    "absolutely", "certainly", "clearly", "obviously",
    "however", "therefore", "meanwhile", "nevertheless",
    "furthermore", "moreover", "additionally", "besides",
    "instead", "otherwise", "indeed", "perhaps",
    "together", "alone", "apart", "aside",
    "whatever", "whenever", "wherever", "whoever",
    "almost", "nearly", "approximately", "roughly",
    "exactly", "precisely", "completely", "totally",
    "entirely", "fully", "partially", "partly",
    "quickly", "slowly", "carefully", "easily",
    "mainly", "mostly", "largely", "widely",
    "directly", "indirectly", "eventually", "finally",
    "immediately", "suddenly", "gradually", "constantly",
    "frequently", "rarely", "occasionally", "regularly",
    "naturally", "normally", "usually", "typically",
    "specially", "especially", "particularly",
    "also", "too", "as", "well", "either", "neither",
    "both", "whether", "rather", "than",
    "about", "across", "against", "around", "behind",
    "below", "beneath", "beside", "beyond", "inside",
    "outside", "within", "without", "along", "among",
    "toward", "towards", "throughout", "upon",
    "able", "unable", "capable", "possible", "impossible",
    "available", "necessary", "essential", "vital", "crucial",
    "correct", "incorrect", "proper", "improper", "appropriate",
    "suitable", "useful", "helpful", "useless", "pointless",
    "meaningful", "meaningless", "important", "unimportant",
    "fine", "cool", "nice", "great", "awesome", "amazing",
    "similar", "identical", "different", "opposite", "reverse",
    "positive", "negative", "neutral", "active", "passive",
    "strong", "weak", "powerful", "gentle", "rough",
    "light", "dark", "bright", "dim", "clear", "cloudy",
    "wet", "dry", "clean", "dirty", "full", "empty",
    "fast", "slow", "quick", "rapid", "sudden",
    "deep", "shallow", "wide", "narrow", "thick", "thin",
    "hard", "soft", "tough", "delicate", "fragile",
    "rich", "poor", "cheap", "expensive", "free",
    "safe", "dangerous", "harmful", "helpful",
    "happy", "sad", "angry", "calm", "excited",
    "tired", "sleepy", "awake", "alert", "energetic",
    "hungry", "thirsty", "full", "healthy", "sick",
    "brave", "scared", "afraid", "nervous", "confident",
    "kind", "mean", "nice", "rude", "polite", "friendly",
    "smart", "clever", "wise", "silly", "funny",
    "beautiful", "ugly", "pretty", "handsome", "cute",
    "young", "old", "new", "ancient", "modern",
    "tall", "short", "long", "wide", "high", "low",
    "big", "small", "tiny", "huge", "massive", "mini",
    "beginner", "intermediate", "advanced", "expert",
    "like", "dislike", "love", "hate", "enjoy", "prefer",
    "wonder", "curious", "interested", "bored",
    "hope", "wish", "dream", "goal", "plan", "aim",
    "practice", "exercise", "train", "prepare",
    "test", "exam", "quiz", "grade", "score",
    "lesson", "topic", "subject", "chapter", "unit",
    "homework", "assignment", "project", "report",
    "essay", "paragraph", "sentence", "grammar",
    "vocabulary", "spelling", "pronunciation",
    "meaning", "definition", "synonym", "antonym",
    "lesson", "course", "class", "lecture", "seminar",
    "degree", "diploma", "certificate",
    "college", "university", "school", "academy",
    "professor", "teacher", "instructor", "tutor",
    "classmate", "friend", "buddy", "partner",
    "library", "lab", "laboratory", "classroom",
    "campus", "dorm", "hostel",
    "schedule", "timetable", "deadline", "due",
    "break", "holiday", "vacation", "summer", "winter",
    "spring", "autumn", "fall", "season",
    "monday", "tuesday", "wednesday", "thursday", "friday",
    "saturday", "sunday", "weekend", "weekday",
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
    "today", "tomorrow", "yesterday", "tonight",
    "morning", "afternoon", "evening", "night", "midnight",
    "hour", "minute", "second", "moment", "instant",
    "past", "present", "future", "now", "then",
    "ago", "later", "soon", "early", "late",
    "once", "twice", "daily", "weekly", "monthly", "yearly",
    # Science terms
    "photosynthesis", "mitochondria", "chloroplast", "respiration",
    "digestion", "circulation", "excretion", "reproduction",
    "adaptation", "evolution", "mutation", "variation",
    "ecosystem", "habitat", "population", "community",
    "predator", "prey", "consumer", "producer", "decomposer",
    "organism", "species", "genus", "family", "order",
    "tissue", "organ", "system", "skeleton", "muscle",
    "neuron", "synapse", "dendrite", "axon", "impulse",
    "hormone", "enzyme", "antibody", "antigen", "vaccine",
    "gravity", "friction", "inertia", "momentum", "velocity",
    "acceleration", "displacement", "amplitude", "frequency",
    "wavelength", "reflection", "refraction", "diffraction",
    "electricity", "magnetism", "current", "voltage",
    "resistance", "conductor", "insulator", "circuit",
    "proton", "neutron", "electron", "isotope", "ion",
    "chemical", "reaction", "equation", "solution",
    "acid", "base", "ph", "salt", "solvent", "solute",
    "oxidation", "reduction", "catalyst", "activation",
    "pressure", "volume", "density", "buoyancy",
    "solar", "lunar", "orbit", "axis", "equator",
    "climate", "weather", "temperature", "humidity",
    "precipitation", "evaporation", "condensation",
    "erosion", "weathering", "deposition", "plate",
    "tectonic", "volcano", "earthquake", "tsunami",
    "mineral", "rock", "fossil", "sediment", "crystal",
    "algebra", "geometry", "calculus", "trigonometry",
    "statistics", "probability", "function", "variable",
    "constant", "coefficient", "theorem", "proof",
    "hypothesis", "theory", "law", "principle",
    "experiment", "observation", "data", "analysis",
    "method", "procedure", "variable", "control",
    "microscope", "telescope", "thermometer", "barometer",
    "computer", "program", "algorithm", "data",
    "software", "hardware", "network", "internet",
    # Geography
    "continent", "ocean", "mountain", "river", "lake",
    "desert", "forest", "jungle", "island", "peninsula",
    "equator", "tropic", "latitude", "longitude", "hemisphere",
    "capital", "population", "border", "region",
    "africa", "asia", "europe", "america", "australia",
    "antarctica", "atlantic", "pacific", "indian", "arctic",
    # Math terms
    "addition", "subtraction", "multiplication", "division",
    "fraction", "decimal", "percentage", "ratio",
    "angle", "triangle", "square", "rectangle", "circle",
    "diameter", "radius", "circumference", "perimeter",
    "area", "volume", "surface", "dimension",
    "parallel", "perpendicular", "intersect", "vertex",
    "horizontal", "vertical", "diagonal", "symmetry",
    # Study / exam
    "multiple", "choice", "select", "match", "fill",
    "blank", "true", "false", "short", "long",
    "option", "choose", "correct", "wrong",
    "point", "mark", "credit", "partial",
    "attempt", "retry", "submit", "check",
    "explain", "describe", "define", "list",
    "summarize", "compare", "contrast", "discuss",
    "identify", "label", "name", "state",
    "diagram", "illustrate", "draw", "label",
    "prove", "show", "solve", "evaluate",
    "calculate", "compute", "determine", "find",
    "derive", "formulate", "express", "represent",
    "classify", "categorize", "organize", "arrange",
    "distinguish", "differentiate", "recognize",
    "infer", "predict", "estimate", "approximate",
    "measure", "plot", "graph", "tabulate",
    "biology", "chemistry", "physics", "geology", "astronomy",
    "botany", "zoology", "ecology", "genetics",
    "literature", "poetry", "prose", "drama", "fiction",
    "novel", "story", "character", "plot", "theme",
    "grammar", "vocabulary", "reading", "writing",
    "listening", "speaking", "comprehension",
    "essay", "paragraph", "thesis", "argument",
    "evidence", "example", "citation", "reference",
    "source", "quote", "paraphrase", "summarize",
    "analyze", "interpret", "evaluate", "judge",
    "appreciate", "understand", "recognize",
    "democracy", "monarchy", "dictatorship", "republic",
    "government", "constitution", "parliament", "president",
    "economy", "market", "trade", "tax", "budget",
    "revolution", "independence", "colonization",
    "civilization", "empire", "kingdom", "dynasty",
    "war", "peace", "treaty", "alliance", "conflict",
    "religion", "culture", "tradition", "custom",
    "philosophy", "ethics", "logic", "reason",
    "psychology", "sociology", "anthropology",
    "technology", "engineering", "innovation",
    "communication", "transportation", "agriculture",
    "industry", "manufacturing", "production",
    "business", "management", "leadership",
    "accounting", "finance", "marketing",
    "education", "training", "development",
    "health", "medicine", "surgery", "therapy",
    "nutrition", "exercise", "fitness", "wellness",
    "disease", "infection", "treatment", "prevention",
    "diagnosis", "symptom", "cause", "effect",
    "research", "discovery", "invention", "patent",
    "journal", "article", "publication", "review",
    "abstract", "introduction", "method", "conclusion",
    "reference", "bibliography", "appendix", "index",
    "plural", "singular", "tense", "verb", "noun",
    "adjective", "adverb", "pronoun", "preposition",
    "conjunction", "interjection", "article",
    "subject", "object", "predicate", "clause",
    "phrase", "sentence", "paragraph", "passage",
    "letter", "word", "syllable", "rhyme",
    "prefix", "suffix", "root", "compound",
    "active", "passive", "conditional", "subjunctive",
    "declarative", "interrogative", "imperative",
    "exclamatory", "affirmative", "negative",
    "metaphor", "simile", "personification", "imagery",
    "alliteration", "onomatopoeia", "hyperbole",
    "dialogue", "monologue", "narrative", "description",
    "protagonist", "antagonist", "setting", "mood",
    "tone", "style", "voice", "perspective",
    "conflict", "climax", "resolution", "theme",
    "moral", "lesson", "message", "symbol",
    "author", "narrator", "reader", "audience",
    "edition", "volume", "chapter", "section",
    "page", "line", "stanza", "verse",
    "cover", "title", "content", "index",
    "biology", "chemistry", "physics", "geography",
    "history", "civics", "economics", "sociology",
    "psychology", "philosophy", "logic",
    "accountancy", "business", "commerce",
    "computer", "informatics", "programming",
    "physical", "chemical", "biological",
    "algorithm", "binary", "decimal", "hexadecimal",
    "variable", "array", "string", "integer", "float",
    "function", "object", "class", "method", "attribute",
    "loop", "condition", "recursion", "iteration",
    "compile", "interpret", "execute", "debug",
    "database", "server", "client", "protocol",
    "memory", "storage", "processor", "cache",
    "keyboard", "mouse", "monitor", "printer",
    "energy", "matter", "space", "time",
    "motion", "rest", "speed", "velocity",
    "acceleration", "deceleration", "momentum",
    "force", "mass", "weight", "density",
    "pressure", "volume", "temperature", "heat",
    "work", "power", "efficiency", "energy",
    "wave", "particle", "field", "quantum",
    "electric", "magnetic", "electromagnetic",
    "circuit", "current", "voltage", "resistance",
    "conductor", "insulator", "semiconductor",
    "lens", "mirror", "prism", "spectrum",
    "opaque", "transparent", "translucent",
    "absorb", "reflect", "refract", "transmit",
    "planet", "star", "galaxy", "nebula",
    "comet", "asteroid", "meteor", "satellite",
    "orbit", "axis", "rotation", "revolution",
    "solar", "lunar", "eclipse", "phase",
    "gravity", "inertia", "friction", "drag",
    "buoyant", "viscous", "elastic", "plastic",
    "solid", "liquid", "gas", "plasma",
    "melt", "freeze", "boil", "evaporate",
    "condense", "sublime", "deposit",
    "atom", "molecule", "element", "compound",
    "mixture", "solution", "suspension", "colloid",
    "acid", "base", "salt", "indicator",
    "metal", "nonmetal", "metalloid", "alloy",
    "corrosion", "rust", "tarnish", "oxidation",
    "crystal", "amorphous", "polymer", "monomer",
    "catalyst", "enzyme", "substrate", "product",
    "reactant", "yield", "equilibrium",
    "cell", "tissue", "organ", "system",
    "nucleus", "membrane", "cytoplasm", "organelle",
    "mitosis", "meiosis", "cytokinesis",
    "gene", "chromosome", "allele", "genotype",
    "phenotype", "dominant", "recessive", "inherit",
    "dna", "rna", "protein", "amino",
    "photosynthesis", "respiration", "fermentation",
    "digestion", "absorption", "assimilation",
    "excretion", "secretion", "ingestion",
    "heart", "brain", "lung", "liver", "kidney",
    "stomach", "intestine", "pancreas", "bladder",
    "artery", "vein", "capillary", "aorta",
    "neuron", "synapse", "reflex", "stimulus",
    "response", "adaptation", "evolution",
    "natural", "selection", "survival", "fitness",
    "predator", "prey", "food", "chain", "web",
    "biome", "ecosystem", "habitat", "niche",
    "population", "community", "species",
    "renewable", "nonrenewable", "sustainable",
    "pollution", "conservation", "biodiversity",
    "erosion", "weathering", "deposition",
    "igneous", "sedimentary", "metamorphic",
    "plate", "tectonic", "fault", "fold",
    "volcano", "magma", "lava", "ash",
    "earthquake", "seismic", "epicenter",
    "weather", "climate", "atmosphere", "troposphere",
    "stratosphere", "ozone", "greenhouse",
    "hurricane", "tornado", "typhoon", "cyclone",
    "monsoon", "drought", "flood", "blizzard",
    "latitude", "longitude", "equator", "meridian",
    "parallel", "tropic", "polar", "temperate",
    "altitude", "elevation", "relief", "topography",
    "map", "globe", "atlas", "compass",
    "scale", "legend", "key", "symbol",
    "direction", "bearing", "coordinate", "grid",
    "urban", "rural", "suburban", "settlement",
    "migration", "immigration", "emigration",
    "population", "density", "distribution",
    "agriculture", "industry", "commerce",
    "transport", "communication", "trade",
    "developed", "developing", "industrialized",
    "resource", "natural", "mineral", "fuel",
    "renewable", "nonrenewable", "sustainable",
    "ancient", "civilization", "medieval", "modern",
    "renaissance", "industrial", "revolution",
    "empire", "kingdom", "republic", "democracy",
    "monarchy", "dictatorship", "colony",
    "invasion", "conquest", "independence",
    "revolution", "reform", "rebellion",
    "treaty", "alliance", "peace", "war",
    "economy", "trade", "commerce", "industry",
    "agriculture", "craft", "manufacture",
    "currency", "market", "tax", "revenue",
    "society", "class", "caste", "status",
    "religion", "philosophy", "ideology",
    "science", "mathematics", "literature",
    "art", "architecture", "music", "dance",
    "sculpture", "painting", "theatre",
    "baroque", "classical", "romantic", "gothic",
    "poem", "play", "novel", "story",
    "drama", "comedy", "tragedy", "satire",
    "verse", "prose", "rhyme", "meter",
    "stanza", "sonnet", "ballad", "epic",
    "plot", "character", "theme", "setting",
    "conflict", "climax", "resolution",
    "moral", "lesson", "irony", "symbol",
    "similarity", "difference", "comparison",
    "contrast", "analogy", "example",
    "evidence", "proof", "example",
    "conclusion", "summary", "opinion", "fact",
    "cause", "effect", "purpose", "reason",
    "problem", "solution", "advantage",
    "disadvantage", "benefit", "drawback",
    "always", "never", "sometimes", "usually",
    "often", "rarely", "frequently", "occasionally",
    "all", "most", "some", "few", "many",
    "much", "little", "several", "numerous",
    "plenty", "enough", "sufficient", "adequate",
    "excessive", "insufficient", "inadequate",
    "correct", "accurate", "precise", "exact",
    "perfect", "flawless", "proper", "appropriate",
    "incorrect", "inaccurate", "wrong", "false",
    "scientific", "method", "hypothesis",
    "experiment", "observation", "conclusion",
    "theory", "law", "principle", "concept",
    "variable", "control", "measurement",
    "qualitative", "quantitative", "objective",
    "subjective", "bias", "valid", "reliable",
}

MIN_WORD_LEN = 3
MAX_SUGGESTIONS = 3
MAX_DISTANCE = 2


def suggest(word: str) -> list[str]:
    """Return suggested corrections for a misspelled word."""
    word = word.lower()
    if word in DICTIONARY:
        return []
    candidates = []
    for entry in DICTIONARY:
        dist = levenshtein(word, entry)
        if 0 < dist <= MAX_DISTANCE:
            candidates.append((dist, entry))
    candidates.sort(key=lambda x: (x[0], x[1]))
    return [w for _, w in candidates[:MAX_SUGGESTIONS]]


def check_text(text: str) -> list[dict]:
    """Check a full text for spelling errors.
    Returns list of {word, suggestions} for each misspelled word.
    """
    words = re.findall(r"[a-zA-Z]+", text)
    errors = []
    for w in words:
        if len(w) < MIN_WORD_LEN:
            continue
        if w.lower() in DICTIONARY:
            continue
        sugs = suggest(w.lower())
        if not sugs:
            # Skip words with no close match (likely proper nouns)
            continue
        errors.append({"word": w, "suggestions": sugs})
    return errors
