/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppQuizzesIndexRouteImport } from './routes/app.quizzes.index'
import { Route as AppSubjectSubjectIdRouteImport } from './routes/app.subject.$subjectId'
import { Route as AppQuizzesNewRouteImport } from './routes/app.quizzes.new'
import { Route as AppQuizzesQuizIdRouteImport } from './routes/app.quizzes.$quizId'
import { Route as AppChapterChapterIdRouteImport } from './routes/app.chapter.$chapterId'
import { Route as AppQuizzesQuizIdResultsRouteImport } from './routes/app.quizzes.$quizId.results'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIndexRoute = AppQuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuizzesRoute,
} as any)
const AppSubjectSubjectIdRoute = AppSubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesNewRoute = AppQuizzesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuizzesRoute,
} as any)
const AppQuizzesQuizIdRoute = AppQuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => AppQuizzesRoute,
} as any)
const AppChapterChapterIdRoute = AppChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesQuizIdResultsRoute = AppQuizzesQuizIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppQuizzesQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/quizzes': typeof AppQuizzesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/chapter/$chapterId': typeof AppChapterChapterIdRoute
  '/app/quizzes/$quizId': typeof AppQuizzesQuizIdRouteWithChildren
  '/app/quizzes/new': typeof AppQuizzesNewRoute
  '/app/subject/$subjectId': typeof AppSubjectSubjectIdRoute
  '/app/quizzes/': typeof AppQuizzesIndexRoute
  '/app/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app': typeof AppIndexRoute
  '/app/chapter/$chapterId': typeof AppChapterChapterIdRoute
  '/app/quizzes/$quizId': typeof AppQuizzesQuizIdRouteWithChildren
  '/app/quizzes/new': typeof AppQuizzesNewRoute
  '/app/subject/$subjectId': typeof AppSubjectSubjectIdRoute
  '/app/quizzes': typeof AppQuizzesIndexRoute
  '/app/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/quizzes': typeof AppQuizzesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/chapter/$chapterId': typeof AppChapterChapterIdRoute
  '/app/quizzes/$quizId': typeof AppQuizzesQuizIdRouteWithChildren
  '/app/quizzes/new': typeof AppQuizzesNewRoute
  '/app/subject/$subjectId': typeof AppSubjectSubjectIdRoute
  '/app/quizzes/': typeof AppQuizzesIndexRoute
  '/app/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/assessment'
    | '/login'
    | '/signup'
    | '/app/leaderboard'
    | '/app/planner'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/subjects'
    | '/app/'
    | '/app/chapter/$chapterId'
    | '/app/quizzes/$quizId'
    | '/app/quizzes/new'
    | '/app/subject/$subjectId'
    | '/app/quizzes/'
    | '/app/quizzes/$quizId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/login'
    | '/signup'
    | '/app/leaderboard'
    | '/app/planner'
    | '/app/settings'
    | '/app/subjects'
    | '/app'
    | '/app/chapter/$chapterId'
    | '/app/quizzes/$quizId'
    | '/app/quizzes/new'
    | '/app/subject/$subjectId'
    | '/app/quizzes'
    | '/app/quizzes/$quizId/results'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/assessment'
    | '/login'
    | '/signup'
    | '/app/leaderboard'
    | '/app/planner'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/subjects'
    | '/app/'
    | '/app/chapter/$chapterId'
    | '/app/quizzes/$quizId'
    | '/app/quizzes/new'
    | '/app/subject/$subjectId'
    | '/app/quizzes/'
    | '/app/quizzes/$quizId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes/': {
      id: '/app/quizzes/'
      path: '/'
      fullPath: '/app/quizzes/'
      preLoaderRoute: typeof AppQuizzesIndexRouteImport
      parentRoute: typeof AppQuizzesRoute
    }
    '/app/subject/$subjectId': {
      id: '/app/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/app/subject/$subjectId'
      preLoaderRoute: typeof AppSubjectSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes/new': {
      id: '/app/quizzes/new'
      path: '/new'
      fullPath: '/app/quizzes/new'
      preLoaderRoute: typeof AppQuizzesNewRouteImport
      parentRoute: typeof AppQuizzesRoute
    }
    '/app/quizzes/$quizId': {
      id: '/app/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/app/quizzes/$quizId'
      preLoaderRoute: typeof AppQuizzesQuizIdRouteImport
      parentRoute: typeof AppQuizzesRoute
    }
    '/app/chapter/$chapterId': {
      id: '/app/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/app/chapter/$chapterId'
      preLoaderRoute: typeof AppChapterChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes/$quizId/results': {
      id: '/app/quizzes/$quizId/results'
      path: '/results'
      fullPath: '/app/quizzes/$quizId/results'
      preLoaderRoute: typeof AppQuizzesQuizIdResultsRouteImport
      parentRoute: typeof AppQuizzesQuizIdRoute
    }
  }
}

interface AppQuizzesQuizIdRouteChildren {
  AppQuizzesQuizIdResultsRoute: typeof AppQuizzesQuizIdResultsRoute
}

const AppQuizzesQuizIdRouteChildren: AppQuizzesQuizIdRouteChildren = {
  AppQuizzesQuizIdResultsRoute: AppQuizzesQuizIdResultsRoute,
}

const AppQuizzesQuizIdRouteWithChildren =
  AppQuizzesQuizIdRoute._addFileChildren(AppQuizzesQuizIdRouteChildren)

interface AppQuizzesRouteChildren {
  AppQuizzesQuizIdRoute: typeof AppQuizzesQuizIdRouteWithChildren
  AppQuizzesNewRoute: typeof AppQuizzesNewRoute
  AppQuizzesIndexRoute: typeof AppQuizzesIndexRoute
}

const AppQuizzesRouteChildren: AppQuizzesRouteChildren = {
  AppQuizzesQuizIdRoute: AppQuizzesQuizIdRouteWithChildren,
  AppQuizzesNewRoute: AppQuizzesNewRoute,
  AppQuizzesIndexRoute: AppQuizzesIndexRoute,
}

const AppQuizzesRouteWithChildren = AppQuizzesRoute._addFileChildren(
  AppQuizzesRouteChildren,
)

interface AppRouteChildren {
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppQuizzesRoute: typeof AppQuizzesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChapterChapterIdRoute: typeof AppChapterChapterIdRoute
  AppSubjectSubjectIdRoute: typeof AppSubjectSubjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppQuizzesRoute: AppQuizzesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChapterChapterIdRoute: AppChapterChapterIdRoute,
  AppSubjectSubjectIdRoute: AppSubjectSubjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
